c_compiler:
  - vs2019                     # [win]

cxx_compiler:
  - vs2019                     # [win]

pybind11_abi:
  - 4

boost:
  - 1.74
vigra:
  - 1.11.1
python:
  - 3.7
  # - 3.8
  # - 3.9
  # - 3.10
