name: deploy

on:
  push:
    tags:
      - '0.*'

jobs:
  package:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          auto-activate-base: true
          activate-environment: bld-env
          environment-file: .github/workflows/etc/bld-environment.yml
          condarc-file: .github/workflows/etc/condarc-deploy.yml
          miniforge-variant: Miniforge3
          use-mamba: true
      - name: linux conda build
        if: matrix.os == 'ubuntu-latest'
        shell: bash -l {0}
        run: conda mambabuild -c conda-forge conda-recipe
      - name: osx conda build
        if: matrix.os == 'macos-latest'
        shell: bash -l {0}
        run:  conda mambabuild -c conda-forge conda-recipe
      - name: windows conda build
        if: matrix.os == 'windows-latest'
        shell: cmd /C CALL {0}
        run: conda mambabuild -c conda-forge conda-recipe
