name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-w-conda-recipe:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true
      - uses: conda-incubator/setup-miniconda@v4
        with:
          activate-environment: "build"
          auto-activate: true
          auto-update-conda: true
          environment-file: .github/workflows/etc/bld-environment.yml
          miniforge-version: latest
          conda-remove-defaults: true
      - name: linux conda build
        if: matrix.os == 'ubuntu-latest'
        shell: bash -l {0}
        run: rattler-build build -c conda-forge -r conda-recipe/recipe.yaml
      - name: osx conda build
        if: matrix.os == 'macos-latest'
        shell: bash -l {0}
        run: rattler-build build -c conda-forge -r conda-recipe/recipe.yaml
      - name: windows conda build
        if: matrix.os == 'windows-latest'
        shell: cmd /C CALL {0}
        run: rattler-build build -c conda-forge -r conda-recipe\recipe.yaml
